[env:uno_r4_wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino

debug_tool = cmsis-dap
build_type = debug
monitor_speed = 115200

build_flags =
    -D configUSE_TRACE_FACILITY=1
    -D configGENERATE_RUN_TIME_STATS=1
    -D configUSE_MUTEXES=1
    -D configTOTAL_HEAP_SIZE=0x3000
    -D portCONFIGURE_TIMER_FOR_RUN_TIME_STATS()=void()
    -D portGET_RUN_TIME_COUNTER_VALUE()=micros()