Unigou Remote: include/logger.h File Reference
logger.h File Reference
Asynchronous logging system based on queues and dedicated tasks. This module manages the creation, queuing, and processing of system logs in a non-blocking manner for the main tasks.
Macros
#define MAX_LOG_MSG_LEN 100
Defines the maximum length of log messages.
Enumerations
enum Level { DEBUG , OPERATION , WARNING , ERROR }
Levels of log severity.
Functions
void log_init ()
Initializes the log queue and the log processing task.
void log_write (Level, const char *)
Creates a log with required fields and sends it to the log queue.
Detailed Description
Asynchronous logging system based on queues and dedicated tasks. This module manages the creation, queuing, and processing of system logs in a non-blocking manner for the main tasks.
Definition in file logger.h.
Macro Definition Documentation
MAX_LOG_MSG_LEN
#define MAX_LOG_MSG_LEN 100
Defines the maximum length of log messages.
Definition at line 12 of file logger.h.
Referenced by log_write().
Enumeration Type Documentation
Level
enum Level
Levels of log severity.
Note
It does not affect the order in which the logs are printed.
Enumerator
DEBUG
OPERATION
WARNING
ERROR
Definition at line 18 of file logger.h.
Function Documentation
log_init()
void log_init ()
Initializes the log queue and the log processing task.
Warning
This function should only be called once, during system initialization and before any call to log_write(). If there is a failure in allocating memory for the log queue or in creating the task for processing the logs, the system will display an error message and enter an infinite loop.
Definition at line 24 of file logger.cpp.
References log_task(), logs, and max_logs.
Referenced by setup().
log_write()
void log_write (Level level, const char * msg)
Creates a log with required fields and sends it to the log queue.
Parameters
[in] level Severity of the log.
[in] message String containing message.
Precondition
The log_init() function should have been executed successfully.
Definition at line 39 of file logger.cpp.
References Log::level, logs, MAX_LOG_MSG_LEN, Log::message, Log::task, and Log::timestamp.
Referenced by mem_task(), TaskA(), TaskB(), TaskController(), TaskMemory(), and tracer_task().