Unigou Remote: src/logger.cpp File Reference
logger.cpp File Reference
Implementation of the asynchronous logger module using FreeRTOS.
#include <Arduino.h>
#include <Arduino_FreeRTOS.h>
#include "logger.h"
Classes
struct Log
Internal structure representing a single log entry packet.
Functions
static void log_task (void *pvParameters)
Dedicated FreeRTOS task that consumes and outputs logs. This task runs in an infinite loop and remains in the Blocked state as long as the log queue is empty, consuming 0% CPU. When a log arrives, it wakes up, formats the data into a CSV-like string, and streams it over the hardware Serial interface.
void log_init ()
Initializes the log queue and the log processing task.
void log_write (Level level, const char *msg)
Creates a log with required fields and sends it to the log queue.
Variables
static QueueHandle_t logs
static const int max_logs = 40
Detailed Description
Implementation of the asynchronous logger module using FreeRTOS.
Definition in file logger.cpp.
Function Documentation
log_init()
void log_init ()
Initializes the log queue and the log processing task.
Warning
This function should only be called once, during system initialization and before any call to log_write(). If there is a failure in allocating memory for the log queue or in creating the task for processing the logs, the system will display an error message and enter an infinite loop.
Definition at line 24 of file logger.cpp.
References log_task(), logs, and max_logs.
Referenced by setup().
log_task()
void log_task (void * pvParameters) static
Dedicated FreeRTOS task that consumes and outputs logs. This task runs in an infinite loop and remains in the Blocked state as long as the log queue is empty, consuming 0% CPU. When a log arrives, it wakes up, formats the data into a CSV-like string, and streams it over the hardware Serial interface.
Definition at line 53 of file logger.cpp.
References Log::level, logs, Log::message, Log::task, and Log::timestamp.
Referenced by log_init().
log_write()
void log_write (Level level, const char * msg)
Creates a log with required fields and sends it to the log queue.
Parameters
[in] level Severity of the log.
[in] message String containing message.
Precondition
The log_init() function should have been executed successfully.
Definition at line 39 of file logger.cpp.
References Log::level, logs, MAX_LOG_MSG_LEN, Log::message, Log::task, and Log::timestamp.
Referenced by mem_task(), TaskA(), TaskB(), TaskController(), TaskMemory(), and tracer_task().
Variable Documentation
logs
QueueHandle_t logs static
Definition at line 10 of file logger.cpp.
Referenced by log_init(), log_task(), and log_write().
max_logs
const int max_logs = 40 static
Definition at line 11 of file logger.cpp.
Referenced by log_init().