Unigou Remote: src/main.cpp File Reference
main.cpp File Reference
#include <Arduino.h>
#include <Arduino_FreeRTOS.h>
#include "logger.h"
#include "mem_monitor.h"
#include "task_tracer.h"
#include "runtime_stats.h"
Macros
#define PRIORITY_LOW 1
#define PRIORITY_MED 2
#define PRIORITY_HIGH 3
Functions
static void TaskA (void *pvParameters)
static void TaskB (void *pvParameters)
static void TaskMemory (void *pvParameters)
static void TaskController (void *pvParameters)
void setup ()
void loop ()
static void consume_stack (int depth)
Variables
SemaphoreHandle_t xResourceMutex
TaskHandle_t xTargetTaskHandle = NULL
Macro Definition Documentation
PRIORITY_HIGH
#define PRIORITY_HIGH 3
Definition at line 10 of file main.cpp.
Referenced by setup().
PRIORITY_LOW
#define PRIORITY_LOW 1
Definition at line 8 of file main.cpp.
Referenced by setup().
PRIORITY_MED
#define PRIORITY_MED 2
Definition at line 9 of file main.cpp.
Referenced by setup().
Function Documentation
consume_stack()
void consume_stack (int depth) static
Definition at line 64 of file main.cpp.
References consume_stack().
Referenced by consume_stack(), and TaskB().
loop()
void loop ()
Definition at line 46 of file main.cpp.
setup()
void setup ()
Definition at line 20 of file main.cpp.
References log_init(), PRIORITY_HIGH, PRIORITY_LOW, PRIORITY_MED, TaskA(), TaskB(), TaskController(), TaskMemory(), tracer_init(), xResourceMutex, and xTargetTaskHandle.
TaskA()
void TaskA (void * pvParameters) static
Definition at line 48 of file main.cpp.
References log_write(), OPERATION, WARNING, and xResourceMutex.
Referenced by setup().
TaskB()
void TaskB (void * pvParameters) static
Definition at line 72 of file main.cpp.
References consume_stack(), log_write(), OPERATION, and xResourceMutex.
Referenced by setup().
TaskController()
void TaskController (void * pvParameters) static
Definition at line 117 of file main.cpp.
References log_write(), OPERATION, WARNING, and xTargetTaskHandle.
Referenced by setup().
TaskMemory()
void TaskMemory (void * pvParameters) static
Definition at line 96 of file main.cpp.
References ERROR, log_write(), and OPERATION.
Referenced by setup().
Variable Documentation
xResourceMutex
SemaphoreHandle_t xResourceMutex
Definition at line 12 of file main.cpp.
Referenced by setup(), TaskA(), and TaskB().
xTargetTaskHandle
TaskHandle_t xTargetTaskHandle = NULL
Definition at line 13 of file main.cpp.
Referenced by setup(), and TaskController().