Unigou Remote: src/mem_monitor.cpp File Reference
mem_monitor.cpp File Reference
Implementation of the periodic memory and task stack monitoring subsystem.
#include <Arduino.h>
#include <Arduino_FreeRTOS.h>
#include "logger.h"
#include "mem_monitor.h"
Functions
static void mem_task (void *pvParameters)
FreeRTOS task that periodically profiles memory and task stack safety. Running as a strict periodic task via vTaskDelayUntil, this function captures the current heap status and uses uxTaskGetSystemState to dynamically list all operational tasks, printing their remaining stack space.
void mem_monitor_init ()
Initializes the memory monitor module and spawns its reporting task.
Variables
static const TickType_t sampling_time = pdMS_TO_TICKS(200)
static const int max_tasks = 10
static size_t free_heap = 0
static size_t minimum_heap = 0
static TaskStatus_t task_status [max_tasks]
Detailed Description
Implementation of the periodic memory and task stack monitoring subsystem.
Definition in file mem_monitor.cpp.
Function Documentation
mem_monitor_init()
void mem_monitor_init ()
Initializes the memory monitor module and spawns its reporting task.
Warning
This function should only be called once, during system initialization and after the logging subsystem has been initialized. If there is a failure in creating the task for processing memory data, the system will display an error message and enter an infinite loop.
Definition at line 20 of file mem_monitor.cpp.
References mem_task().
mem_task()
void mem_task (void * pvParameters) static
FreeRTOS task that periodically profiles memory and task stack safety. Running as a strict periodic task via vTaskDelayUntil, this function captures the current heap status and uses uxTaskGetSystemState to dynamically list all operational tasks, printing their remaining stack space.
Definition at line 31 of file mem_monitor.cpp.
References free_heap, log_write(), max_tasks, minimum_heap, OPERATION, sampling_time, and task_status.
Referenced by mem_monitor_init().
Variable Documentation
free_heap
size_t free_heap = 0 static
Definition at line 14 of file mem_monitor.cpp.
Referenced by mem_task().
max_tasks
const int max_tasks = 10 static
Definition at line 12 of file mem_monitor.cpp.
Referenced by mem_task().
minimum_heap
size_t minimum_heap = 0 static
Definition at line 15 of file mem_monitor.cpp.
Referenced by mem_task().
sampling_time
const TickType_t sampling_time = pdMS_TO_TICKS(200) static
Definition at line 11 of file mem_monitor.cpp.
Referenced by mem_task().
task_status
TaskStatus_t task_status[max_tasks] static
Definition at line 16 of file mem_monitor.cpp.
Referenced by mem_task().