Unigou Remote: src/task_tracer.cpp File Reference
task_tracer.cpp File Reference
Implementation of the lock-free kernel event tracer.
#include "task_tracer.h"
#include "logger.h"
#include <Arduino_FreeRTOS.h>
Classes
struct TraceEvent
Data packet encapsulating a single captured kernel trace event.
Macros
#define TRACER_BUFFER_SIZE 128
Functions
static void tracer_task (void *pvParameters)
High-priority background FreeRTOS task processing trace logs. This task wakes up periodically every 50ms, evaluates if any new events have been pushed into the ring buffer, formats them, and forwards them to the centralized system logger module.
static const char * state_to_string (int state)
Internal translation utility converting state integer IDs into strings.
void tracer_init ()
Initializes the task tracer subsystem and its reporting mechanism.
void tracer_log_from_hook (const char *taskName, int state)
Low-level hook function called by the FreeRTOS kernel to log state changes. This function acts as the bridge between FreeRTOS internal kernel events and user-space tracing logic.
Variables
static TraceEvent traceBuffer [TRACER_BUFFER_SIZE]
static volatile uint32_t head = 0
static volatile uint32_t tail = 0
Detailed Description
Implementation of the lock-free kernel event tracer.
Definition in file task_tracer.cpp.
Macro Definition Documentation
TRACER_BUFFER_SIZE
#define TRACER_BUFFER_SIZE 128
Definition at line 10 of file task_tracer.cpp.
Referenced by tracer_log_from_hook(), and tracer_task().
Function Documentation
state_to_string()
const char * state_to_string (int state) static
Internal translation utility converting state integer IDs into strings.
Parameters
[in] state The integer value of the state transition.
Returns
const char* A pointer to the corresponding static flash string literal.
Definition at line 34 of file task_tracer.cpp.
Referenced by tracer_task().
tracer_init()
void tracer_init ()
Initializes the task tracer subsystem and its reporting mechanism.
Warning
This function should only be called once, during system initialization and after the logging subsystem has been initialized. If there is a failure in creating the task for task tracing, the system will display an error message and enter an infinite loop.
Definition at line 45 of file task_tracer.cpp.
References tracer_task().
Referenced by setup().
tracer_log_from_hook()
void tracer_log_from_hook (const char * taskName, int state)
Low-level hook function called by the FreeRTOS kernel to log state changes. This function acts as the bridge between FreeRTOS internal kernel events and user-space tracing logic.
Parameters
[in] taskName The string pointer containing the name of the tracked task.
[in] state The integer ID representing the target state transition.
Note
Implements C-linkage so it can be called seamlessly from inside the native C files of the FreeRTOS core.
Definition at line 53 of file task_tracer.cpp.
References head, tail, traceBuffer, and TRACER_BUFFER_SIZE.
tracer_task()
void tracer_task (void * pvParameters) static
High-priority background FreeRTOS task processing trace logs. This task wakes up periodically every 50ms, evaluates if any new events have been pushed into the ring buffer, formats them, and forwards them to the centralized system logger module.
Definition at line 68 of file task_tracer.cpp.
References head, log_write(), OPERATION, state_to_string(), tail, traceBuffer, and TRACER_BUFFER_SIZE.
Referenced by tracer_init().
Variable Documentation
head
volatile uint32_t head = 0 static
Definition at line 23 of file task_tracer.cpp.
Referenced by tracer_log_from_hook(), and tracer_task().
tail
volatile uint32_t tail = 0 static
Definition at line 25 of file task_tracer.cpp.
Referenced by tracer_log_from_hook(), and tracer_task().
traceBuffer
TraceEvent traceBuffer[TRACER_BUFFER_SIZE] static
Definition at line 21 of file task_tracer.cpp.
Referenced by tracer_log_from_hook(), and tracer_task().